Fix `kci-dev results builds` command
Fix the below error related to missing command line
options in command `builds` definition.
```
File "kcidev/subcommands/results/options.py", line 117, in wrapper
   return func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
TypeError: builds() got an unexpected keyword argument 'hardware'
```
Issue introduced by PR: https://github.com/kernelci/kci-dev/pull/175

Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>